# Exported from Render on 2024-04-01T11:04:44Z
services:
  - type: web
    name: render
    runtime: docker
    repo: https://github.com/Benedict086005/render
    branch: main
    plan: free
    envVars:
      - key: DEBUG
        sync: False
      - key: SECRET_KEY
        sync: secret_key
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
